FROM node:14.15.4

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

RUN yarn global add expo-cli
# ENV REACT_NATIVE_PACKAGER_HOSTNAME "192.168.0.6"
ENV REACT_NATIVE_PACKAGER_HOSTNAME="192.168.0.4"